GET http://localhost:8081/api/v1/helloworld

###

GET http://localhost:8081/api/v1/helloworld

###

GET http://localhost:8081/api/v1/hello

###

GET http://localhost:8081/api/v1/hello?name=Rob

###

GET http://localhost:8081/api/v1/hello?age=12

###

GET http://localhost:8081/api/v1/hello?name=Rob&age=12

###

GET http://localhost:8081/api/v1/hello/Rob

###

POST http://localhost:8081/api/v1/hello/Rob

###

GET http://localhost:8081/api/v1/hello/Rob/12

###

POST http://localhost:8081/api/v1/hello/Rob/12
